[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/sudhanshu-portfolio" 

[functions]
  directory = "netlify/functions"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"


